typedef [EnforceRange] unsigned long GPUBufferDynamicOffset;
typedef [EnforceRange] unsigned long GPUStencilValue;
typedef [EnforceRange] unsigned long GPUSampleMask;
typedef [EnforceRange] long GPUDepthBias;

typedef [EnforceRange] unsigned long long GPUSize64;
typedef [EnforceRange] unsigned long GPUIntegerCoordinate;
typedef [EnforceRange] unsigned long GPUIndex32;
typedef [EnforceRange] unsigned long GPUSize32;
typedef [EnforceRange] long GPUSignedOffset32;

typedef unsigned long long GPUSize64Out;
typedef unsigned long GPUIntegerCoordinateOut;
typedef unsigned long GPUSize32Out;

typedef boolean myBool;
typedef ByteString myByteString;
typedef DOMString myDOMString;
typedef USVString myUSVString;
typedef byte myByte;
typedef octet myOctet;
typedef short myShort;
typedef unsigned short myUnsignedShort;
typedef long myLong;
typedef unsigned long myUnsignedLong;
typedef long long myLongLong;
typedef unsigned long long myUnsignedLongLong;
typedef float myFloat;
typedef unrestricted float myUnrestrictedFloat;
typedef double myDouble;
typedef unrestricted double myUnrestrictedDouble;

typedef FrozenArray<long> frozenArray;
