interface SomeObject {
    readonly attribute unsigned long someValue;
    static undefined takeResource(SomeObject obj);
};

dictionary SomeDict {
    required SomeObject obj;
    SomeObject optionalObj;
    required sequence<SomeObject> sequenceObj;
    required sequence<SomeObject?> sequenceOfOptionalObj;
    sequence<SomeObject> optionalOfSequenceObj;
    // named resources don't get `borrow`.
    required namedObject named;
};

typedef (SomeObject or long) SomeUnion;

typedef SomeObject namedObject;
