interface singleton {
  undefined singleParam(DOMString str);
  undefined singleParam(long num);
  undefined multipleParams(DOMString str1, DOMString str2);
  undefined multipleParams(long num1, long num2);
};
interface resource {
  undefined singleParam(DOMString str);
  undefined singleParam(long num);
  undefined multipleParams(DOMString str1, DOMString str2);
  undefined multipleParams(long num1, long num2);
};
