
# cargo-vet config file

[cargo-vet]
version = "0.10"

[policy.webidl2wit]
audit-as-crates-io = true

[policy.webidl2wit-cli]
audit-as-crates-io = true

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.18"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.10"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.2"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.6"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.86"
criteria = "safe-to-deploy"

[[exemptions.bstr]]
version = "1.11.3"
criteria = "safe-to-run"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.23"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.23"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.18"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.11"
criteria = "safe-to-run"

[[exemptions.diff]]
version = "0.1.13"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "1.0.0"
criteria = "safe-to-run"

[[exemptions.equivalent]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.2"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.id-arena]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.7.0"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.171"
criteria = "safe-to-run"

[[exemptions.log]]
version = "0.4.22"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "5.1.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.pretty_assertions]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.86"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.36"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-run"

[[exemptions.semver]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.210"
criteria = "safe-to-run"

[[exemptions.serde_derive]]
version = "1.0.210"
criteria = "safe-to-run"

[[exemptions.similar]]
version = "2.7.0"
criteria = "safe-to-run"

[[exemptions.similar-asserts]]
version = "1.7.0"
criteria = "safe-to-run"

[[exemptions.strsim]]
version = "0.11.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.71"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.12"
criteria = "safe-to-deploy"

[[exemptions.unicode-segmentation]]
version = "1.12.0"
criteria = "safe-to-run"

[[exemptions.unicode-xid]]
version = "0.2.6"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.webidl2wit]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.webidl2wit-cli]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.weedle]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wit-encoder]]
version = "0.229.0"
criteria = "safe-to-deploy"

[[exemptions.wit-parser]]
version = "0.229.0"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"
