interface GPUAdapterInfo {
    constructor(double radius);
    long requestAdapter(optional GPURequestAdapterOptions options = {});
    readonly attribute DOMString foo;
    attribute DOMString bar;
    static readonly attribute DOMString bar;
    static attribute DOMString biz;
    undefined withList(sequence<long> w);
    undefined union((long or double) num);
    undefined unionSame((DOMString or ByteString) val);
};
interface OnlyFoo {
    long foo();
};
dictionary GPURequestAdapterOptions {
    GPUPowerPreference powerPreference;
    boolean forceFallbackAdapter = false;
};
enum GPUPowerPreference {
    "low-power",
    "high-performance",
};
typedef long MyLong;
